version: "3.9"

services:
  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "8082:8082"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - /etc/letsencrypt:/etc/letsencrypt:ro
  #   depends_on:
  #     - frontend
  #   restart: always

  fe-tsubame:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fe-tsubame
    ports:
      - "8081:8081"
    restart: always

  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - /etc/letsencrypt:/etc/letsencrypt
  #     - /var/lib/letsencrypt:/var/lib/letsencrypt
